name: Metrics
on:
  # 1. Runs every hour
  schedule: [{cron: "0 * * * *"}]
  # 2. Allows you to run it manually
  workflow_dispatch:
  # 3. Runs when you push to master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (Standard)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ebram-gerges
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo
          
          # üé® THEME: Dracular (Dark & Clean)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # üêç LANGUAGES (Detailed breakdown)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          
          # ‚è±Ô∏è WAKATIME (Your coding stats)
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages
